# Generated by Django 6.0.7 on 2026-09-12 09:25

from django.db import migrations, models


def merge_patient_and_volunteer_into_user(apps, schema_editor):
    """
    CerviBloom collapsed its three account roles (Patient, Volunteer, Admin)
    into two (User, Admin): any signed-in account can now do what a Patient
    or Volunteer could before. Existing accounts carry over their data
    unchanged; only the role label on PATIENT/VOLUNTEER accounts becomes USER.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role__in=['PATIENT', 'VOLUNTEER']).update(role='USER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
        migrations.RunPython(merge_patient_and_volunteer_into_user, migrations.RunPython.noop),
    ]
