# Generated by Django 6.0.7 on 2026-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hpv_vaccine_doses',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '1 dose'), ('2', '2 doses'), ('unsure', 'Not sure')], help_text='Self-reported, optional.', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_screening_year',
            field=models.CharField(blank=True, help_text="e.g. '2023', 'never', or 'before2015'. Self-reported, optional.", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('SW', 'Kiswahili')], help_text="Applied to the site's language toggle right after sign-up; optional.", max_length=2),
        ),
    ]
