# Generated by Django 6.0.7 on 2026-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myth', models.CharField(help_text='The false belief, stated plainly.', max_length=255)),
                ('fact', models.TextField(help_text='The correction, medically grounded.')),
                ('category', models.CharField(choices=[('VACCINE', 'HPV vaccine'), ('SCREENING', 'Screening'), ('TRANSMISSION', 'Transmission & risk'), ('TREATMENT', 'Treatment'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
