# Generated by Django 6.0.7 on 2026-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mythfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Structured yes/no answers keyed by question'),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='risk_tier',
            field=models.CharField(blank=True, choices=[('ROUTINE', 'Routine'), ('DISCUSS', 'Discuss at next visit'), ('SEEK_CARE', 'Seek care soon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='symptoms',
            field=models.CharField(blank=True, help_text="Auto-generated summary of the 'yes' answers", max_length=500),
        ),
    ]
