# Generated by Django 6.0.7 on 2026-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_symptomlog_answers_symptomlog_risk_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='hpv_vaccine_stock',
            field=models.CharField(choices=[('UNKNOWN', 'Not reported'), ('IN_STOCK', 'In stock'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='pap_smear_kit_stock',
            field=models.CharField(choices=[('UNKNOWN', 'Not reported'), ('IN_STOCK', 'In stock'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock')], default='UNKNOWN', max_length=20),
        ),
    ]
