# Generated by Django 6.0.7 on 2026-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facility_hpv_vaccine_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If set, the donor asked not to be named in any public acknowledgement.'),
        ),
    ]
