# Generated by Django 6.0.7 on 2026-09-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donationrecord_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='services_sw',
            field=models.CharField(blank=True, help_text='Kiswahili translation of `services`. Optional; the English list is shown if this is blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_sw',
            field=models.TextField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English answer.'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_sw',
            field=models.CharField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English question.', max_length=255),
        ),
        migrations.AddField(
            model_name='mythfact',
            name='fact_sw',
            field=models.TextField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English fact.'),
        ),
        migrations.AddField(
            model_name='mythfact',
            name='myth_sw',
            field=models.CharField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English myth.', max_length=255),
        ),
    ]
