# Generated by Django 6.0.7 on 2026-09-12 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facility_services_sw_faqitem_answer_sw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(help_text='Short teaser shown in the article list.', max_length=400)),
                ('body', models.TextField(help_text='Full article text.')),
                ('source_name', models.CharField(blank=True, help_text="Where this is drawn from, e.g. 'WHO Africa' or 'IARC/HPV Information Centre'.", max_length=150)),
                ('source_url', models.URLField(blank=True, help_text='Link to the original source, if any.')),
                ('title_sw', models.CharField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English title.', max_length=255)),
                ('summary_sw', models.CharField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English summary.', max_length=400)),
                ('body_sw', models.TextField(blank=True, help_text='Kiswahili translation. Optional; falls back to the English body.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='core.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
