# Generated by Django 6.0.7 on 2026-09-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('PUBLIC', 'Public Hospital'), ('PRIVATE', 'Private Clinic'), ('NGO', 'NGO Clinic'), ('HEALTH_CENTRE', 'Health Centre')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='open_days',
            field=models.CharField(blank=True, help_text="Optional, e.g. 'Mon - Fri'.", max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='open_hours',
            field=models.CharField(blank=True, help_text="Optional, e.g. '8:00 AM - 5:00 PM'.", max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional; shown as a Call button when set.', max_length=30),
        ),
    ]
