# Generated by Django 6.0.7 on 2026-09-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facility_facility_type_facility_open_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('PREVENTION', 'Prevention'), ('SCREENING', 'Screening'), ('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('RESEARCH', 'Research'), ('WELLBEING', 'Wellbeing'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
