# Generated by Django 6.0.7 on 2026-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='message',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability',
            field=models.CharField(choices=[('WEEKENDS', 'Weekends only'), ('WEEKDAYS', 'Weekdays'), ('FLEXIBLE', 'Flexible'), ('EVENTS_ONLY', 'Events only')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Clinical & Medical'), ('NON_MEDICAL', 'Community & Outreach')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='county',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='credentials_file',
            field=models.FileField(blank=True, help_text='Professional credentials (e.g. KMPDC license) for medical roles. Optional.', null=True, upload_to='volunteer_credentials/'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='motivation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='phone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='role',
            field=models.CharField(default='', help_text="e.g. 'Screening Nurse', from the fixed role catalog shown on the page.", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Submitted'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Not selected')], default='PENDING', max_length=20),
        ),
    ]
