# Generated by Django 6.0.7 on 2026-09-15 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_volunteerapplication_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='donor_name',
            field=models.CharField(blank=True, help_text="Only used for a guest (not signed in) donation's public leaderboard credit.", max_length=150),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
